### ISSUE TITLE
Base schema not resolving from $ref

### ISSUE THREAD

**Issue by Jeroen-VDW** [gregsdennis/json-everything#432]
**Using the sandbox: https://json-everything.net/json-schema**
- Nuget Package: JsonSchema.Net
- Nuget Version: 4.03
- OS: Windows

**Describe the bug**
Exception is thrown when trying to validate against a valid Schema when using $ref keyword in the root.

**To Reproduce**
Json schema:
`{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"$ref": "#/definitions/Order",
	"definitions": {
		"Order": {
			"type": "object",
			"additionalProperties": true,
			"properties": {
				"orderId": {
					"type": "string",
					"format": "uuid"
				}
			},
			"required": [
				"orderId"
			],
			"title": "Order"
		}
	}
}`

Test data:
`{
	"orderId": "3cb65f2d-4049-43c1-b185-1943765acd9"
}`

Click "Validate" => nothing seems to happen but if you open the browser console you will see the following error:
![image](https://user-images.githubusercontent.com/108151935/233072950-556d5b84-a284-422a-bd3d-b233322f4ce5.png)
Got the same error when trying to implement it myself.

**Expected behavior**
No exception should be thrown, test data should validate to false with a message like "String '3cb65f2d-4049-43c1-b185-1943765acd9' does not validate against format 'uuid'."

**Additional context**
Tried the same scenario on a validator that uses the Newtonsoft Schema, which results in correct validation.
![image](https://user-images.githubusercontent.com/108151935/233072706-64976d81-668d-4ea4-aff9-ee23eaeaeac6.png)

**Comment by gregsdennis** [comment]
I've been able to reproduce this in a unit test.  I'm not sure what's going on here.

Some time ago, we added `$id` to all of the tests, but this case doesn't have one.  It's probably to do with something there.

**Comment by gregsdennis** [comment]
Discussing with my JSON Schema partners, it looks like the problem here is that for drafts 6 and 7, any keywords alongside `$ref` need to be ignored.

That's normally fine, except when the `$ref` is at the root.  What is ignored?  Do we ignore `definitions` as a keyword, or is it merely a location in some JSON data?  Do we ignore `$schema`?  I think probably not.

---

As a workaround, if you can use any draft later than draft 7 (draft 2019-09 or later), this will resolve properly.

---

Lastly, I really need to get the website set up to handle exceptions better.

**Comment by gregsdennis** [comment]
I've pushed the fix for the library.  v4.0.4 should be available soon, and it should be working in the playground as soon as that redeploys.

I'll work on handling exceptions better in the website in the future.

**Comment by Jeroen-VDW** [comment]
Thank you for the quick intervention! However I'm afraid the issue is not fully resolved. My original case does indeed work, but now I get a similar error on the next nested level for a more complex Schema.

**Schema:**
`{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"$ref": "#/definitions/Order",
	"definitions": {
		"Order": {
			"type": "object",
			"additionalProperties": true,
			"properties": {
				"orderId": {
					"type": "string",
					"format": "uuid"
				},
				"customer": {
					"$ref": "#/definitions/Customer"
				}
			},
			"required": [
				"customer",
				"orderId"
			],
			"title": "Order"
		},
		"Customer": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"name": {
					"type": "string"
				}
			},
			"required": [
				"name"
			],
			"title": "Customer"
		}
	}
}`

**Input:**
`{
	"orderId": "3cb65f2d-4049-4c1-b185-194365acdf99",
	"customer": {
		"name": "Some Customer"
	}
}`

**Result:**
`Cannot resolve base schema from `https://json-everything.net/cf854ddc9b#/definitions/Customer``

**Comment by gregsdennis** [comment]
🤔 I wonder if I just need to remove the draft 6/7 condition when setting the base URI...  It's important in validation, but it may not be important for that first pass.

**Comment by gregsdennis** [comment]
That didn't work, but I do have a fix.  It'll be coming shortly.

**Comment by dodexahedron** [comment]
I'm pretty sure I just ran into this as well, on version 4.1.0 from nuget. Or at least I _think_ it's the same or at least a related issue.
 
I have two local schema documents, with my local "root" schema having a $ref to another local schema for the "items" element of an array.

The problem seems to go away if I remove the $schema element from my schemas and then manually register them in the global schema registry, but then they're not really fully formal schemas any more, in a vacuum, since they don't truly resolve to a root schema beyond the local schemas. They validate with JsonEverything, because it is _told_ to validate it against a specific root schema, but that still seems non-ideal, since other parsers in theory won't be able to validate _my_ root schema without also being explicitly told to use a specific root schema.

If I don't remove the metaschemas from my documents, JsonEverything throws an exception stating that it failed to resolve the referenced schema document, yet it's showing the exact correct path to the file it says it can't resolve, and the $id at the root of that file matches the $ref in the root schema. It won't even let me register them in the global schema registry if I leave the metaschemas in them.

Side note about workarounds involving using newer schemas than draft 7 as well as (not related to this issue) #310 : It seems visual studio 2022 _still_ doesn't natively support newer schemas than draft 7 for intellisense (unless I'm missing something), and I haven't found any extensions that help that situation, so that is unfortunate.

**Comment by gregsdennis** [comment]
I just pushed an update that handles URIs a bit better in \*nix systems.  Please see if that fixes your problem.

**Comment by dodexahedron** [comment]
Made a correction to my last comment. It's not an array in my current schema. It's the "additionalProperties" element of an element at the root, with a ref to the schema for the objects allowed in that element.

I'll check the latest update out.

**Comment by dodexahedron** [comment]
Looks like 4.1.1 has resolved the issue.
I put the metaschema elements back in and everything validates as expected.

Thanks!

The only remaining issue that keeps visual studio 2022 from liking it is visual studio wants an empty fragment on uri-references to local files for whatever reason.
So, there will be `"$ref": "MySchema.json#"` to make visual studio work.
But, that results in JsonEverything failing to resolve the file (the exception shows the file path having the \#, so maybe that just needs to get trimmed when resolving files?).

If you'd like a new issue for that, I'll be happy to open one and show files that cause the problem.

**Comment by gregsdennis** [comment]
I wouldn't follow VS's suggestions.  Do what works at runtime.

There's a VSCode extension that uses my lib to provide 2020-12 validation.  You can find a link on the JSON Schema website implementations page, under editors, I think.

**Comment by dodexahedron** [comment]
Yeah, it's lame. Easy enough to put the # in when editing files to make VS happy and then remove it for release. 😅

It's disappointing that, when they "fixed" the json schema validation relatively recently, they only went as far as draft-07. 🙄

The project happens to be targeted at *nix environments anyway, so VSCode working with it is great for release. I'm just developing on VS because I'm addicted to ReSharper.

Thanks again.

**Comment by gregsdennis** [comment]
I'm addicted to R# as well. 😆

**Comment by dodexahedron** [comment]
A further thought about the file resolution, though.

In theory, wouldn't a reference to a section within a file be a technically valid uri-reference?

Example: `"$ref": "MySchema.json#/Some/Path"`

If it's treating the `#` as part of the file name, that would probably fail, as well, no?

**Comment by gregsdennis** [comment]
I'm asking my JSON Schema team.

**Comment by dodexahedron** [comment]
Draft 07 at least makes it look valid, but not recommended, since it uses a "SHOULD NOT" instead of a "MUST NOT" for it being an empty fragment.

I haven't looked at more recent drafts yet, for that specific item, but that's what I found when I was originally troubleshooting my schema, to see if I had it right.

I'll have a look at that later.

Have a great weekend!
